services:
    laravel.test:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mongo
#            - redis
#            - minio
#            - mailpit
#            - selenium
    mongo:
        image: 'mongo'
        build:
            context: ./docker/mongodb
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${DB_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
            MONGO_INITDB_DATABASE: '${DB_DATABASE}'
        ports:
            - 27017:27017
        extra_hosts:
            - "host.docker.internal:host-gateway"
        command: 'mongod --config /etc/mongod.conf'
        healthcheck:
            test: |
                test $$(mongosh --quiet -u '${DB_USERNAME}' -p '${DB_PASSWORD}' --eval "try { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'mongo' }] }).ok } catch (_) { rs.status().ok }") -eq 1
            interval: 10s
            start_period: 30s
        volumes:
            - 'sail-mongo:/data/db'
            - "sail-mongo-config:/data/configdb"
        networks:
            - sail
#    redis:
#        image: 'redis:alpine'
#        ports:
#            - '${FORWARD_REDIS_PORT:-6379}:6379'
#        volumes:
#            - 'sail-redis:/data'
#        networks:
#            - sail
#        healthcheck:
#            test:
#                - CMD
#                - redis-cli
#                - ping
#            retries: 3
#            timeout: 5s
#    minio:
#        image: 'minio/minio:latest'
#        ports:
#            - '${FORWARD_MINIO_PORT:-9000}:9000'
#            - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
#        environment:
#            MINIO_ROOT_USER: sail
#            MINIO_ROOT_PASSWORD: password
#        volumes:
#            - 'sail-minio:/data/minio'
#        networks:
#            - sail
#        command: 'minio server /data/minio --console-address ":8900"'
#        healthcheck:
#            test:
#                - CMD
#                - curl
#                - '-f'
#                - 'http://localhost:9000/minio/health/live'
#            retries: 3
#            timeout: 5s
#    mailpit:
#        image: 'axllent/mailpit:latest'
#        ports:
#            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
#            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
#        networks:
#            - sail
#    selenium:
#        image: selenium/standalone-chrome
#        extra_hosts:
#            - 'host.docker.internal:host-gateway'
#        volumes:
#            - '/dev/shm:/dev/shm'
#        networks:
#            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mongo:
        driver: local
    sail-mongo-config:
        driver: local
#    sail-redis:
#        driver: local
#    sail-minio:
#        driver: local
